# Site settings
title: Rain
description: "Rain is a simple and clean Jekyll theme with focus on content."
url: https://github.com/heikopanjas/rain-jekyll-theme

# Author
author:
  name: Heiko Panjas
  email: heiko@panjas.com
  url: https://panjas.com

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink: /:year-:month-:day/:title
paginate: 5

# Related posts settings
related_posts_section:
  max_count: 5
  min_common_tags: 2

# Links to social media
social:
  email: heiko@panjas.com
  github: https://github.com/heikopanjas
  mastodon: https://chaos.social/@joe_viterbo
  linkedin: https://www.linkedin.com/in/heiko-panjas-440433253/
